### ISSUE TITLE
Doesn't work for (at least) London and Frankfurt regions

### ISSUE THREAD

**Issue by tomfanning** [PressLabs/z3#13]
With a London bucket:

`[root@backup1 ~]# z3 backup --full --dry-run
Traceback (most recent call last):
  File "/usr/bin/z3", line 9, in <module>
    load_entry_point('z3==0.1.14', 'console_scripts', 'z3')()
  File "/usr/lib/python2.7/site-packages/z3/snap.py", line 562, in main
    bucket = boto.connect_s3(s3_key_id, s3_secret, **extra_config).get_bucket(bucket)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 471, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 518, in head_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request

[root@backup1 ~]# export S3_USE_SIGV4="True"

[root@backup1 ~]# z3 backup --full --dry-run
Traceback (most recent call last):
  File "/usr/bin/z3", line 9, in <module>
    load_entry_point('z3==0.1.14', 'console_scripts', 'z3')()
  File "/usr/lib/python2.7/site-packages/z3/snap.py", line 562, in main
    bucket = boto.connect_s3(s3_key_id, s3_secret, **extra_config).get_bucket(bucket)
  File "/usr/lib/python2.7/site-packages/boto/__init__.py", line 140, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 196, in __init__
    "When using SigV4, you must specify a 'host' parameter."
boto.s3.connection.HostRequiredError: BotoClientError: When using SigV4, you must specify a 'host' parameter.`

I believe you are suffering from this bug
https://github.com/boto/boto/issues/2916
https://github.com/boto/boto/issues/2741

**Comment by rciorba** [comment]
@tomfanning Thanks for the bug report!

**Comment by mwpastore** [comment]
Same with US East (Ohio). I was able to work around it by creating an inifile named .boto in the user's home directory:

```ini
[s3]
use-sigv4=True
host=s3.us-east-2.amazonaws.com
```

**Comment by IronFarm** [comment]
Thanks @mwpastore . I was passing `s3.amazonaws.com` as my host and adding the region fixed my issue.
