### ISSUE TITLE
dose this support China region?

### ISSUE THREAD

**Issue by laolongju** [presslabs/z3#33]
I try to test Z3 in China Region,  the test is failed cause by the 403 Forbidden.
I replace the bucket with Tokyo region, the test can be success.
----------------------------
Traceback (most recent call last):
  File "/usr/local/bin/z3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 587, in main
    bucket = boto.connect_s3(s3_key_id, s3_secret, **extra_config).get_bucket(bucket)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 509, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 542, in head_bucket
    raise err
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden

**Comment by rciorba** [comment]
If boto supports the china region, then z3 should as well. 
Also according to the FAQ https://www.amazonaws.cn/en/about-aws/china/faqs/ you need a separate set of credentials to access AWS China.
