### ISSUE TITLE
z3 fails when doing anything other than 'status'!

### ISSUE THREAD

**Issue by brandonpoc** [presslabs/z3#35]
Python version: 2.7.16
OS: Linux (Debian 10.4)

The following error occurs whether running z3 obtained via 'pip install', (0.2.0) (on the OS and python version specified) or via git clone of the latest repository here on github.com.

```
root:~# z3 backup --dry-run
Traceback (most recent call last):
  File "/usr/local/bin/z3", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 607, in main
    dry=args.dry, compressor=compressor, parseable=args.parseable)
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 504, in do_backup
    uploaded = pair_manager.backup_incremental(snap_name=snap_name, dry_run=dry)
  File "/usr/local/lib/python2.7/dist-packages/z3/snap.py", line 387, in backup_incremental
    z_snap.parent.name, z_snap.name),
AttributeError: 'NoneType' object has no attribute 'name'

```

Again,  I get this error whether using the version installed with 'pip' on my Linux distribution OR via download. I can use 'z3 status' and I see snapshots I have not yet backed up (I haven't used z3 at all, this is my first experience):

```
-> # z3 status
backup status for mydatastorage/testtank@snap* on MY-S3-BUCKET/z3-backup/
NAME  | PARENT | TYPE    | HEALTH | LOCAL STATE | SIZE
snap1 | -      | missing | -      | ok          |
snap2 | -      | missing | -      | ok          |

```

My /etc/z3_backup/z3.conf file looks like so:

```
[main]
BUCKET=MY-S3-BUCKET
S3_KEY_ID=my-key
S3_SECRET=my-secret
CONCURRENCY=4
CHUNK_SIZE=256M
MAX_RETRIES=3
COMPRESSOR=pigz1
S3_STORAGE_CLASS=STANDARD_IA
SNAPSHOT_PREFIX=snap
FILESYSTEM=mydatastorage/testtank

```

Any ideas what is wrong here?

Thanks

**Comment by Fyb3roptik** [comment]
use the env variables BUCKET, AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY instead of putting them in the config file.

As for the rror you are having, run `zfs list -t all` and send me that info
