### ISSUE TITLE
Plans for python3

### ISSUE THREAD

**Issue by karlbunch** [presslabs/z3#38]
Are there plans to port to python3 ?

On debian:bullseye you can "pip install z3" but because it's under python3 you are greeted with:

```
z3 status
Traceback (most recent call last):
  File "/usr/local/bin/z3", line 5, in <module>
    from z3.snap import main
  File "/usr/local/lib/python3.9/dist-packages/z3/snap.py", line 14, in <module>
    from z3.config import get_config
  File "/usr/local/lib/python3.9/dist-packages/z3/config.py", line 1, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

This is due to the renaming of ConfigParser module to configparser, there could be other issues, I'm curious if anyone is planning to scrub z3 for python3 support?

**Comment by AHerridge** [comment]
I ran into this issue too. My solution was to install pip for python 2.7 (guide: https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/) and then do "pip2 install z3".

**Comment by mrx23dot** [comment]
+1 for python3 support

**Comment by jgartrel** [comment]
I submitted pull request #42 to cover this.  Let's hope it gets merged.
