### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JohnPeacockMessageSystems** [PressLabs/z3#5]
Just trying to do a basic backup, I get a mostly unhelpful stacktrace:

```
[root@pkgrepo1 ecbuild]# z3 backup 
Traceback (most recent call last):
  File "/usr/local/bin/z3", line 9, in <module>
    load_entry_point('z3==0.1.13', 'console_scripts', 'z3')()
  File "/usr/local/lib/python2.7/site-packages/z3/snap.py", line 575, in main
    dry=args.dry, compressor=compressor, parseable=args.parseable)
  File "/usr/local/lib/python2.7/site-packages/z3/snap.py", line 480, in do_backup
    uploaded = pair_manager.backup_incremental(snap_name=snap_name, dry_run=dry)
  File "/usr/local/lib/python2.7/site-packages/z3/snap.py", line 341, in backup_incremental
    z_snap = self._snapshot_to_backup(snap_name)
  File "/usr/local/lib/python2.7/site-packages/z3/snap.py", line 270, in _snapshot_to_backup
    z_snap = self.zfs_manager.get_latest()
  File "/usr/local/lib/python2.7/site-packages/z3/snap.py", line 214, in get_latest
    return self._snapshots.values()[-1]
```

If I execute the same command that is ultimately called internally, that works:

```
zfs list -Ht snap -o 'name,used,refer,mountpoint,written'
pkgrepo@zfs-auto-snap_daily-2016-06-01-2022	0	27.2K	-	27.2K
pkgrepo/mrepo@zfs-auto-snap_daily-2016-06-01-2022	75.1K	17.9G	-	17.9G
pkgrepo/mrepo-cache@zfs-auto-snap_daily-2016-06-01-2022	141K	305M	-	305M
pkgrepo/repo@zfs-auto-snap_daily-2016-06-01-2022	709K	81.3G	-	81.3G
pkgrepo/www@zfs-auto-snap_daily-2016-06-01-2022	7.35M	1.67G	-	1.67G
```

Any suggestions?

**Comment by JohnPeacockMessageSystems** [comment]
Never mind.  I'm an idiot and had the snapshot_prefix wrong.  It would be much nicer to fail gracefully here and say "Nothing to backup" instead of a cryptic backtrace.

**Comment by rciorba** [comment]
@JohnPeacockMessageSystems Thanks for the feedback! Sorry i didn't see it sooner, I'm no longer working with Presslabs and forgot to watch this repo specifically.

You're right, the user friendliness could be improved. I'll send them a PR this week with some improvements.
